
#服务器端口
server:
  port: 8110

#数据源配置
spring:
  datasource:
    url: ${xiaozao.datasource.flow.url}
    username: ${xiaozao.datasource.flow.username}
    password: ${xiaozao.datasource.flow.password}

  # 激活环境
  profiles:
    active: local

  application:
    name: Galaxy